# Broker 所属集群名称
brokerClusterName=DefaultCluster

# Broker 名称
brokerName=broker-a

# Broker ID (0 表示 Master)
brokerId=0

# NameServer 地址
namesrvAddr=rocketmq-namesrv:9876

# 是否允许自动创建 Topic
autoCreateTopicEnable=true

# 是否允许自动创建订阅组
autoCreateSubscriptionGroup=true

# Broker 对外服务的监听端口
listenPort=10911

# 删除文件时间点，默认凌晨4点
deleteWhen=04

# 文件保留时间，默认48小时
fileReservedTime=48

# commitLog 每个文件的大小默认1G
mapedFileSizeCommitLog=1073741824

# ConsumeQueue 每个文件默认存30W条，根据业务情况调整
mapedFileSizeConsumeQueue=300000

# 限制的消息大小
maxMessageSize=65536

# Broker 的角色
# - ASYNC_MASTER 异步复制Master
# - SYNC_MASTER 同步双写Master
# - SLAVE
brokerRole=ASYNC_MASTER

# 刷盘方式
# - ASYNC_FLUSH 异步刷盘
# - SYNC_FLUSH 同步刷盘
flushDiskType=ASYNC_FLUSH

# 检查事务消息，如果超过这个时间还没回查就丢弃
transactionCheckInterval=60000
